source 'https://rubygems.org'
ruby "2.1.1"

gem 'rails', '4.2.0'
gem 'spring', :group => :development

gem 'thin'
gem 'pg'
gem 'devise'
gem 'devise_token_auth', git: 'https://github.com/lynndylanhurley/devise_token_auth.git'
gem 'simple_token_authentication'
gem 'active_model_serializers', '~> 0.8.3'
gem 'rack-cors', :require => 'rack/cors'
gem 'omniauth-twitter'

group :development do
  gem 'dotenv-rails'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
